name: Production CI/CD
description: A CI/CD workflow for production environments

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  prod-ci-cd:
    uses: pixelwolf-org/pixelwolf-actions/.github/workflows/web-prod-ci-cd.yml@main
    secrets: inherit