name: Next.js CI Workflow

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - name: Install dependencies
        run: bun install

      - name: Format code
        run: bun x prettier --write .

      - name: Lint
        run: bun x next lint

      - name: Build
        run: bun x next build