name: Production CI/CD
description: A CI/CD that should run whenever a pull request to main is closed

on:
  workflow_call:
    inputs:
      app-id:
        required: true
        type: string
      branch-name:
        required: false
        type: string
        description: "stage"
      aws-region:
        required: true
        type: string
        description: "AWS Region"
      role-arn:
        required: true
        type: string
        description: "AWS OIDC Role ARN"

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  ci:
    uses: pixelwolf-org/pixelwolf-actions/workflows/web-ci@feature/web-ci-cd

  deploy:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role-arn }}
          aws-region: ${{ inputs.aws-region }}

      - name: Deploy to AWS Amplify
        uses: pixelwolf-org/pixelwolf-actions/actions/amplify-deploy@main
        with:
          app-id: ${{ inputs.app-id }}
          branch-name: ${{ inputs.branch-name }}
          create-branch: "false"

  clean-up:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.head_ref != 'stage' && github.head_ref != 'main' && github.ref_name != 'stage' && github.ref_name != 'main'
    steps:
      - name: Setup AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role-arn }}
          aws-region: ${{ inputs.aws-region }}

      - name: Delete Feature Amplify Branch
        uses: pixelwolf-org/pixelwolf-actions/actions/amplify-branch-delete@main
        with:
          branch-name: ${{ github.head_ref || github.ref_name }}
          app-id: ${{ inputs.app-id }}