name: 'Web CI Workflow'

on:
  workflow_call:
    inputs:
      should-run-unit-tests:
        description: 'Should run unit tests'
        required: false
        default: 'true'
        type: string
      should-run-e2e-tests:
        description: 'Should run E2E tests'
        required: false
        default: 'false'
        type: string

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      packages: read

    steps:
      - uses: actions/checkout@v4

      # - name: 'Setup Node.js'
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 'latest'
      #     # cache: npm
      #     registry-url: 'https://npm.pkg.github.com'

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@pixelwolf-org'
          BUN_AUTH_TOKEN: ${{ github.token }}

      - name: 'Install dependencies'
        run: bun install
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

      - name: 'Run format (Prettier) check'
        run: bun run format-check

      - name: 'Lint'
        run: bun run lint

      - name: 'Build web app'
        run: bun run build

      - name: 'Run unit tests'
        if: ${{ inputs.should-run-unit-tests == 'true' }}
        run: bun run test

      - name: 'Install Playwright Chromium browser'
        if: ${{ inputs.should-run-e2e-tests == 'true' }}
        run: bunx playwright install chromium --with-deps

      - name: 'Run Playwright tests'
        if: ${{ inputs.should-run-e2e-tests == 'true' }}
        run: bunx playwright test
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

      - name: 'Upload Playwright report'
        if: ${{ inputs.should-run-e2e-tests == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
