name: 'Production CI/CD'
description: 'A CI/CD that should run whenever a pull request to main is closed'

on:
  workflow_call:
    inputs:
      org-id:
        description: 'Vercel Organization ID'
        required: true
        type: string
      project-id:
        description: 'Vercel Project ID'
        required: true
        type: string
      environment:
        description: 'Environment to deploy (e.g., preview, production)'
        default: 'preview'
        type: string
        required: false
      prod:
        description: 'Should build production build'
        required: false
        default: 'false'
        type: string
      should-run-unit-tests:
        description: 'Should run unit tests'
        required: false
        default: 'true'
        type: string
      should-run-e2e-tests:
        description: 'Should run E2E tests'
        required: false
        default: 'false'
        type: string

permissions:
  id-token: write
  contents: write
  pull-requests: write
  packages: read
  issues: write

jobs:
  ci:
    uses: pixelwolf-org/pixelwolf-actions/.github/workflows/web-ci.yml@main
    with:
      should-run-unit-tests: ${{ inputs.should-run-unit-tests }}
      should-run-e2e-tests: ${{ inputs.should-run-e2e-tests }}
    secrets: inherit

  cd:
    needs: ci
    runs-on: ubuntu-latest
    outputs:
      deployment-url: ${{ steps.vercel-deploy.outputs.deployment-url }}
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Vercel Deploy'
        id: vercel-deploy
        uses: pixelwolf-org/pixelwolf-actions/.github/actions/vercel-deploy@main
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          org-id: ${{ inputs.org-id }}
          project-id: ${{ inputs.project-id }}
          environment: ${{ inputs.environment }}

  deploy-comment:
    runs-on: ubuntu-latest
    needs: cd
    if: ${{ inputs.environment == 'preview' }}
    steps:
      - name: Comment URL to PR
        uses: actions/github-script@v6
        id: add-preview-url-comment
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🎉 Your deployment is live! Check it out at: ${{ needs.cd.outputs.deployment-url }} 🚀"
            })
