name: Web Preview Branches CI/CD
description: A CI/CD that runs on Stage for Feature previews branches.

on:
  workflow_call:

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  ci:
    uses: pixelwolf-org/pixelwolf-actions/.github/workflows/web-ci.yml@feature/web-ci-cd

  deploy-preview:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to AWS Amplify
        uses: pixelwolf-org/pixelwolf-actions/actions/amplify-deploy@feature/web-ci-cd
        with:
          app-id: ${{ secrets.AWS_STAGE_AMPLIFY_APP_ID }}
          branch-name: ${{ github.head_ref || github.ref_name }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-arn: ${{ secrets.AWS_STAGE_DEPLOY_OIDC_ROLE_ARN }}
          create-branch: "true"
