name: 'Web CI Workflow'

on:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: 'Generate Token'
        id: gh-app-token
        uses: pixelwolf-org/pixelwolf-actions/.github/actions/gh-app-access-token@main
        with:
          app-id: '1141682'
          installation-id: '60963877'
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      
      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ steps.gh-app-token.outputs.access-token }}" > ~/.npmrc

      - name: 'Install dependencies'
        run: npm install

      - name: 'Run format (Prettier) check'
        run: npm run format-check

      - name: 'Lint'
        run: npm run lint

      - name: 'Build'
        run: npm run build

        