name: 'Web CI Workflow'

on:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      packages: read

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          registry-url: "https://npm.pkg.github.com/"
          scope: "@pixelwolf-org"

      - name: 'Install dependencies'
        run: bun install --frozen-lockfile
        shell: bash
        env:
          BUN_AUTH_TOKEN: ${{ github.token }}

      - name: 'Run format (Prettier) check'
        run: bun run format-check

      - name: 'Lint'
        run: bun run lint

      - name: 'Build'
        run: bun run build

        