name: 'Web CD Workflow'
description: 'CD workflow for web app deployment to Vercel'

on:
  workflow_call:
    inputs:
      env-s3-path:
        description: 'Path to the environment file in S3 bucket'
        required: true
        type: string
      org-id:
        description: 'Vercel organization ID'
        required: true
        type: string
      project-id:
        description: 'Vercel project ID'
        required: true
        type: string
      environment:
        description: 'Deployment environment (preview, production)'
        required: false
        default: 'preview'
        type: string
      prod:
        description: 'Should build production build'
        required: false
        default: 'false'
        type: string
    outputs:
      deployment-url:
        description: 'URL of the deployed application'
        value: ${{ jobs.cd.outputs.deployment-url }}

permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write
  packages: read

jobs:
  cd:
    runs-on: ubuntu-latest
    outputs:
      deployment-url: ${{ steps.vercel-deploy.outputs.deployment-url }}
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: Setup aws credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_STAGE_DEPLOY_OIDC_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 'Download environment file from S3'
        uses: pixelwolf-org/pixelwolf-actions/.github/actions/s3-to-env@main
        with:
          env-s3-path: ${{ inputs.env-s3-path }}

      - name: 'Vercel Deploy'
        id: vercel-deploy
        uses: pixelwolf-org/pixelwolf-actions/.github/actions/vercel-deploy@main
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          org-id: ${{ inputs.org-id }}
          project-id: ${{ inputs.project-id }}
          environment: ${{ inputs.environment }}
          prod: ${{ inputs.prod }}

  deploy-comment:
    runs-on: ubuntu-latest
    needs: cd
    if: ${{ inputs.environment == 'preview' && github.event_name == 'pull_request' }}
    steps:
      - name: Comment URL to PR
        uses: actions/github-script@v6
        id: add-preview-url-comment
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🎉 Your deployment is live! Check it out at: ${{ needs.cd.outputs.deployment-url }} 🚀"
            })
