name: Web Stage CI/CD
description: A CI/CD that runs on Stage and Feature previews enviroments.

on:
  workflow_call:
    inputs:
      app-id:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      role-arn:
        required: true
        type: string

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  ci:
    uses: pixelwolf-org/pixelwolf-actions/.github/workflows/web-ci.yml@feature/web-ci-cd

  deploy-preview:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to AWS Amplify
        uses: pixelwolf-org/pixelwolf-actions/actions/amplify-deploy@feature/web-ci-cd
        with:
          app-id: ${{ inputs.app-id }}
          branch-name: ${{ github.head_ref || github.ref_name }}
          aws-region: ${{ inputs.aws-region }}
          role-arn: ${{ inputs.role-arn }}
          create-branch: "true"
