name: "Production CI/CD"
description: "A CI/CD that should run whenever a pull request to main is closed"

on:
  workflow_call:
    inputs:
      org-id:
        description: "Vercel Organization ID"
        required: true
        type: string
      project-id:
        description: "Vercel Project ID"
        required: true
        type: string
      environment:
        description: "Environment to deploy (e.g., preview, production)"
        default: "preview"
        type: string
        required: false
      prod:
        description: "Should build production build"
        required: false
        default: "false"
        type: string

permissions:
  id-token: write
  contents: write
  pull-requests: write
  packages: read

jobs:
  ci:
    uses: pixelwolf-org/pixelwolf-actions/.github/workflows/web-ci.yml@feature/web-ci-cd

  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Vercel Deploy"
        uses: pixelwolf-org/pixelwolf-actions/.github/actions/vercel-deploy@feature/web-ci-cd
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          environment: ${{ inputs.environment }}
          org-id: ${{ inputs.org-id }}
          project-id: ${{ inputs.project-id }}
