name: 'AWS Amplify Deploy'
description: 'Deploy to AWS Amplify'

inputs:
  app-id:
    description: 'Amplify app ID'
    required: true
  branch-name:
    description: 'Branch name to deploy'
    required: true
  create-branch:
    description: 'Create branch if it doesnt exist'
    required: false
    default: 'false'
  access-token:
    description: 'GitHub Access Token'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: 'Setup build spec'
      shell: bash
      run: |
        sed -i 's|<NPM_TOKEN>|${{ inputs.access-token }}|g' ./buildspec.yml

    - name: 'Update token'
      shell: bash
      if: ${{ inputs.access-token != '' }}
      run: |
        aws amplify update-app \
            --app-id ${{ inputs.app-id }} \
            --build-spec "$(cat ./buildspec.yml)"

    - name: 'Create AWS Amplify Feature Branch'
      if: ${{ inputs.create-branch == 'true' }}
      shell: bash
      run: |
        aws amplify create-branch --app-id ${{ inputs.app-id }} \
            --branch-name ${{ inputs.branch-name }} \
            --no-enable-auto-build \
            --enable-pull-request-preview || true

    - name: 'Deploy to AWS Amplify'
      shell: bash
      run: |
        aws amplify start-job --app-id ${{ inputs.app-id }} \
            --branch-name ${{ inputs.branch-name }} \
            --job-type RELEASE

branding:
  icon: 'upload-cloud'
  color: 'orange'
